config/routes.rb
Rails.application.routes.draw do

  resources :boards do
    resources :lists do
      resources :items
    end
  end



  root 'boards#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
    belongs_to :user
    has_many :lists
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :items
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  # GET /boards/new
  def new
    @board = Board.new
  end

  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)
    @board.user_id = current_user.id
    respond_to do |format|
      if @board.save
        format.html { redirect_to :controller => "boards", :action => "index", notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:name, :list)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :set_list
  before_action :set_board
  before_action :authenticate_user!

  # GET /items
  # GET /items.json
  def index
    @items = @list.items.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.list_id = @list.id
    respond_to do |format|
      if @item.save
        format.html { redirect_to [@board,@list,@item], notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: [@board,@list,@item] }
      else
        format.html { render :new }
        format.json { render json: [@board,@list,@item].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to [@board,@list,@item], notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: [@board,@list,@item] }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to board_list_items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_board
      @board = Board.find(params[:board_id])
    end

    def set_list
      @list = List.find(params[:list_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_action :set_board
  before_action :authenticate_user!



  # GET /lists
  # GET /lists.json
  def index
    @lists = @board.lists.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to [@board,@list], notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to [@board,@list], notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to board_lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    def set_board
      @board = Board.find(params[:board_id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, :board_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true) do |form| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>


</div class="ui middle aligned aligned grid">
  <div class="ui main container">
  <h1>Boards</h1>
    <table class="ui selectable left aligned table small ">
      <thead>
        <tr class="ui selectabled black">
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @boards.each do |board| %>
          <tr class="ui left aligned table gray">
            <td><%= link_to board.name, board_lists_path(board_id: board.id), :class => "ui button primary" %></td>
            <td><%= link_to 'Edit', edit_board_path(board), :class => "ui button primary"  %></td>
            <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?'}, :class => "ui button primary" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New Board', new_board_path, :class => "ui button primary aligned center" %>

  </div>
</div>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @board.name %>
</p>


<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>

app/views/items/_form.html.erb
<%= form_with(model: [@board, @list, @item], local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', board_list_items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>


</div class="ui middle aligned aligned grid">
  <div class="ui main container">
  <h1>Items</h1>
<table class="ui selectable left aligned table small ">
  <thead>
    <tr class="ui selectabled black">
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr class="ui left aligned table gray">
        <td><%= item.name %></td>
        <td><%= link_to 'Back', board_lists_path, :class => "ui button primary" %></td>
        <td><%= link_to 'Edit', edit_board_list_item_path(id: item.id), :class => "ui button primary" %></td>
        <td><%= link_to 'Destroy', [@board,@list,@item], method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui button primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_board_list_item_path, :class => "ui button primary center" %>
  </div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', board_list_items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>


<%= link_to 'Edit', edit_board_list_item_path(@item) %> |
<%= link_to 'Back', board_list_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [@board, @list], local: true) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
    <%= form.hidden_field :board_id, {value: params[:board_id]} %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Show', [@board,@list] %> |
<%= link_to 'Back', board_lists_path %>

app/views/lists/index.html.erb
<p id="notice"><%= notice %></p>


</div class="ui middle aligned aligned grid">
  <div class="ui main container">
  <h1>Lists</h1>
<table class="ui selectable left aligned table small ">
  <thead>
    <tr class="ui selectabled black">
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lists.each do |list| %>
      <tr class="ui left aligned table gray">
        <td><%= link_to list.name, board_list_items_path(list_id: list.id), :class => "ui button primary" %></td>
        <td><%= link_to 'Back', boards_path(), :class => "ui button primary" %></td>
        <td><%= link_to 'Edit', edit_board_list_path(id: list.id), :class => "ui button primary" %></td>
        <td><%= link_to 'Destroy', board_list_path(id: list.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "ui button primary" %></td>
      </tr>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_board_list_path(board_id: params[:board_id]), :class => "ui button primary center" %>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form', list: @list %>

<%= link_to 'Back', board_lists_path %>

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @list.name %>
</p>

<%= link_to 'Edit', edit_board_list_path(@list) %> |
<%= link_to 'Back', board_lists_path %>